# Generated by Django 6.0.4 on 2026-04-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'pair_number'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pair_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('date', 'pair_number', 'group')},
        ),
    ]
