# Generated by Django 6.0.4 on 2026-04-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_lesson_options_alter_lesson_unique_together_and_more'),
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.teacher', verbose_name='Преподаватель'),
        ),
    ]
