# Generated by Django 6.0.4 on 2026-04-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('Н', 'Н (не был)'), ('зач', 'зач'), ('н\\зач', 'н\\зач'), ('', '—')], default='', max_length=10, verbose_name='Оценка'),
        ),
    ]
